- name: Pre-req configuration
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  tasks:
    - name: Disable Swap
      ansible.builtin.shell: /usr/sbin/swapoff -a
      args:
        executable: /bin/bash
      # changed_when: true

    - name: Disable swap in fstab
      ansible.posix.mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Set SELinx mode as permissive
      ansible.posix.selinux:
        policy: targeted
        state: permissive

    - name: Add overlay kernel module
      community.general.modprobe:
        name: overlay
        state: present
        persistent: present

    - name: Add br_netfilter kernel module
      community.general.modprobe:
        name: br_netfilter
        state: present
        persistent: present

    - name: Add all kube nodes to host file
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      loop:
        - { name: master, ip: 192.168.1.101 }
        - { name: worker1, ip: 192.168.1.111 }
        - { name: worker2, ip: 192.168.1.112 }

    - name: Add kernel parameter for kubernetes
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/k8s.conf
      loop:
        - { name: net.bridge.bridge-nf-call-iptables, value: '1'}
        - { name: net.ipv4.ip_forward, value: '1'}
        - { name: net.bridge.bridge-nf-call-ip6tables, value: '1'}
